const ERROR_NO_USER = 'ERROR_NO_USER';
const ERROR_ADDRESS_TAKEN = 'ERROR_ADDRESS_TAKEN';
const ERROR_WRONG_EMAIL = 'ERROR_WRONG_EMAIL';
const WRONG_JWT = 'WRONG_JWT';
const ERROR_WHILE_CHEKING_JWT = 'ERROR_WHILE_CHEKING_JWT';
const MISSING_AUTHORRIZATION_HEADER = 'MISSING_AUTHORRIZATION_HEADER';

module.exports = {
	ERROR_NO_USER,
	ERROR_ADDRESS_TAKEN,
	ERROR_WRONG_EMAIL,
	WRONG_JWT,
	ERROR_WHILE_CHEKING_JWT,
	MISSING_AUTHORRIZATION_HEADER,
};
