const ERROR_NO_USER = 'ERROR_NO_USER';
const ERROR_ADDRESS_TAKEN = 'ERROR_ADDRESS_TAKEN';
const ERROR_WRONG_EMAIL = 'ERROR_WRONG_EMAIL';
const WRONG_JWT = 'WRONG_JWT';

module.exports = {
	ERROR_NO_USER,
	ERROR_ADDRESS_TAKEN,
	ERROR_WRONG_EMAIL,
	WRONG_JWT,
};
